// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";

export class Game {
    "id": string;
    "name": string;
    "cover_url": string;

    /**
     * 刮削封面的远程源地址，本地封面不可用时用于回退
     */
    "cover_source_url": string;
    "company": string;
    "summary": string;

    /**
     * 游戏评分（统一按 10 分制存储）
     */
    "rating": number;

    /**
     * 发售日期（源站原始日期字符串）
     */
    "release_date": string;

    /**
     * 启动路径
     */
    "path": string;

    /**
     * 游戏根目录，不一定是启动文件的上一级
     */
    "game_directory": string;

    /**
     * 存档目录路径
     */
    "save_path": string;

    /**
     * 实际监控的进程名（当启动器和游戏进程不同时使用）
     */
    "process_name": string;

    /**
     * macOS 专用：兼容层类型（system/crossover）
     */
    "wine_runner": string;

    /**
     * macOS 专用：追加给 Wine 的启动参数
     */
    "wine_args": string;

    /**
     * macOS 专用：WINEPREFIX 或 CrossOver bottle 名
     */
    "wine_prefix": string;

    /**
     * 启动方式: normal, steam, compatibility
     */
    "launch_mode": enums$0.LaunchMode;

    /**
     * 本机 Steam 启动标识：原生 AppID 或非 Steam 快捷方式的长 ID
     */
    "steam_launch_id": string;

    /**
     * 本机关联类型：native 或 shortcut
     */
    "steam_launch_kind": string;

    /**
     * 非 Steam 快捷方式所属的 Steam account ID
     */
    "steam_user_id": string;

    /**
     * 游戏状态: not_started, want_to_play, playing, completed, on_hold
     */
    "status": enums$0.GameStatus;

    /**
     * "local", "bangumi", "vndb", "ymgal", "steam", "hikarinagi"
     */
    "source_type": enums$0.SourceType;
    "cached_at": string;
    "source_id": string;
    "created_at": string;
    "updated_at": string;

    /**
     * 是否使用 Locale Emulator 转区启动
     */
    "use_locale_emulator": boolean;

    /**
     * 是否使用 Magpie 超分辨率缩放
     */
    "use_magpie": boolean;

    /**
     * 是否为 NSFW 游戏
     */
    "is_nsfw": boolean;

    /**
     * 是否锁定远程元数据更新
     */
    "metadata_locked": boolean;

    /**
     * 最近一次游玩开始时间（由 play_sessions 聚合）
     */
    "last_played_at"?: string | null;

    /** Creates a new Game instance. */
    constructor($$source: Partial<Game> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("cover_source_url" in $$source)) {
            this["cover_source_url"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("rating" in $$source)) {
            this["rating"] = 0;
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("game_directory" in $$source)) {
            this["game_directory"] = "";
        }
        if (!("save_path" in $$source)) {
            this["save_path"] = "";
        }
        if (!("process_name" in $$source)) {
            this["process_name"] = "";
        }
        if (!("wine_runner" in $$source)) {
            this["wine_runner"] = "";
        }
        if (!("wine_args" in $$source)) {
            this["wine_args"] = "";
        }
        if (!("wine_prefix" in $$source)) {
            this["wine_prefix"] = "";
        }
        if (!("launch_mode" in $$source)) {
            this["launch_mode"] = enums$0.LaunchMode.$zero;
        }
        if (!("steam_launch_id" in $$source)) {
            this["steam_launch_id"] = "";
        }
        if (!("steam_launch_kind" in $$source)) {
            this["steam_launch_kind"] = "";
        }
        if (!("steam_user_id" in $$source)) {
            this["steam_user_id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = enums$0.GameStatus.$zero;
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = enums$0.SourceType.$zero;
        }
        if (!("cached_at" in $$source)) {
            this["cached_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("use_locale_emulator" in $$source)) {
            this["use_locale_emulator"] = false;
        }
        if (!("use_magpie" in $$source)) {
            this["use_magpie"] = false;
        }
        if (!("is_nsfw" in $$source)) {
            this["is_nsfw"] = false;
        }
        if (!("metadata_locked" in $$source)) {
            this["metadata_locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     */
    static createFrom($$source: any = {}): Game {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Game($$parsedSource as Partial<Game>);
    }
}

/**
 * GameBackup 游戏存档备份记录（基于文件系统，不使用数据库）
 */
export class GameBackup {
    /**
     * 备份文件路径（作为唯一标识）
     */
    "path": string;

    /**
     * 文件名
     */
    "name": string;
    "game_id": string;

    /**
     * 备份文件大小（字节）
     */
    "size": number;

    /**
     * 创建时间（来自文件修改时间）
     */
    "created_at": string;

    /** Creates a new GameBackup instance. */
    constructor($$source: Partial<GameBackup> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameBackup instance from a string or object.
     */
    static createFrom($$source: any = {}): GameBackup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameBackup($$parsedSource as Partial<GameBackup>);
    }
}

/**
 * GameProgress 游玩进度记录
 */
export class GameProgress {
    "id": string;
    "game_id": string;
    "chapter": string;
    "route": string;
    "progress_note": string;

    /**
     * none | chapter_end | route_end | full
     */
    "spoiler_boundary": string;
    "updated_at": string;

    /** Creates a new GameProgress instance. */
    constructor($$source: Partial<GameProgress> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = "";
        }
        if (!("route" in $$source)) {
            this["route"] = "";
        }
        if (!("progress_note" in $$source)) {
            this["progress_note"] = "";
        }
        if (!("spoiler_boundary" in $$source)) {
            this["spoiler_boundary"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): GameProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameProgress($$parsedSource as Partial<GameProgress>);
    }
}

export class GameTag {
    "id": string;
    "game_id": string;
    "name": string;

    /**
     * 'bangumi' | 'vndb' | 'ymgal' | 'steam' | 'hikarinagi' | 'user'
     */
    "source": string;
    "weight": number;
    "is_spoiler": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new GameTag instance. */
    constructor($$source: Partial<GameTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("weight" in $$source)) {
            this["weight"] = 0;
        }
        if (!("is_spoiler" in $$source)) {
            this["is_spoiler"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameTag instance from a string or object.
     */
    static createFrom($$source: any = {}): GameTag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameTag($$parsedSource as Partial<GameTag>);
    }
}

export class PlaySession {
    "id": string;
    "game_id": string;
    "start_time": string;
    "end_time": string;

    /**
     * seconds
     */
    "duration": number;
    "updated_at": string;

    /** Creates a new PlaySession instance. */
    constructor($$source: Partial<PlaySession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("start_time" in $$source)) {
            this["start_time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("end_time" in $$source)) {
            this["end_time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaySession instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaySession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaySession($$parsedSource as Partial<PlaySession>);
    }
}

export class User {
    "id": string;
    "created_at": string;

    /**
     * "s3" or "docker"
     */
    "default_backup_target": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("default_backup_target" in $$source)) {
            this["default_backup_target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
