/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --env-file=.dev.vars.example --include-runtime=false` (hash: 9b1ad5cbf44d4cde3454c1728fe693e9)
interface __BaseEnv_Env {
	UPDATE_BUCKET: R2Bucket;
	UPDATE_DB: D1Database;
	ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_TOKEN">> {}
}
