// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../net/http/models.js";

export function Disconnect(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(3081268836).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAuthStatus(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(108553198).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProfile(): $CancellablePromise<vo$0.BangumiProfile> {
    return $Call.ByID(1724367731).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Init(db: sql$0.DB | null, config: appconf$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(88275912, db, config);
}

export function SetEventEmitter(emit: any): $CancellablePromise<void> {
    return $Call.ByID(738585948, emit);
}

export function SetHTTPClient(client: http$0.Client | null): $CancellablePromise<void> {
    return $Call.ByID(4173631033, client);
}

export function SetNowFunc(now: any): $CancellablePromise<void> {
    return $Call.ByID(3444416260, now);
}

export function SetOAuthClientCredentials(clientID: string, clientSecret: string): $CancellablePromise<void> {
    return $Call.ByID(3922631132, clientID, clientSecret);
}

export function SetOpenURLFunc(openURL: any): $CancellablePromise<void> {
    return $Call.ByID(1571817481, openURL);
}

export function StartAuth(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(713098480).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.BangumiAuthStatus.createFrom;
const $$createType1 = vo$0.BangumiProfile.createFrom;
