// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";

/**
 * ExportLogsZip 将 logs 目录导出为 ZIP 压缩包。
 */
export function ExportLogsZip(): $CancellablePromise<string> {
    return $Call.ByID(2112339621);
}

export function GetAppConfig(): $CancellablePromise<appconf$0.AppConfig> {
    return $Call.ByID(1842078622).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Init(db: sql$0.DB | null, config: appconf$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3103773297, db, config);
}

/**
 * OpenDataDirectory 在系统文件管理器中打开 LunaBox 数据目录。
 */
export function OpenDataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2980986610);
}

/**
 * SafeQuit 安全退出应用（绕过托盘最小化逻辑）
 */
export function SafeQuit(): $CancellablePromise<void> {
    return $Call.ByID(1997131465);
}

/**
 * SaveCroppedBackgroundImage 保存裁剪后的背景图片
 * srcPath 应为 /local/backgrounds/temp_bg_xxx.png 格式的路径
 */
export function SaveCroppedBackgroundImage(srcPath: string, x: number, y: number, width: number, height: number): $CancellablePromise<string> {
    return $Call.ByID(812601970, srcPath, x, y, width, height);
}

/**
 * SelectAndCropBackgroundImage 打开文件选择对话框选择背景图片，复制到临时目录并返回 /local/ 路径供前端裁剪
 */
export function SelectAndCropBackgroundImage(): $CancellablePromise<string> {
    return $Call.ByID(2708947883);
}

/**
 * SelectBackgroundImage 打开文件选择对话框选择背景图片，并保存到应用目录
 */
export function SelectBackgroundImage(): $CancellablePromise<string> {
    return $Call.ByID(1768685136);
}

/**
 * SelectDirectory 打开目录选择对话框
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(2840589822, title);
}

export function SetConfigUpdateHook(hook: any): $CancellablePromise<void> {
    return $Call.ByID(3643617081, hook);
}

/**
 * SetQuitHandler 设置安全退出回调
 */
export function SetQuitHandler(handler: any): $CancellablePromise<void> {
    return $Call.ByID(815395438, handler);
}

export function SetSuppressInitialWindowShow(suppress: boolean): $CancellablePromise<void> {
    return $Call.ByID(625660891, suppress);
}

export function ShouldShowMainWindowOnReady(): $CancellablePromise<boolean> {
    return $Call.ByID(1504236708);
}

export function UpdateAppConfig(newConfig: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(3160634607, newConfig);
}

// Private type creation functions
const $$createType0 = appconf$0.AppConfig.createFrom;
