// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetHomePageData(): $CancellablePromise<vo$0.HomePageData> {
  return $Call.ByID(2525952338).then(($result: any) => {
    return $$createType0($result);
  });
}

export function GetOrCreateCurrentUser(): $CancellablePromise<models$0.User> {
  return $Call.ByID(2185879951).then(($result: any) => {
    return $$createType1($result);
  });
}

export function Init(
  db: sql$0.DB | null,
  config: appconf$0.AppConfig | null,
): $CancellablePromise<void> {
  return $Call.ByID(2602836072, db, config);
}

// Private type creation functions
const $$createType0 = vo$0.HomePageData.createFrom;
const $$createType1 = models$0.User.createFrom;
