// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortableSetupService exposes lunacli PATH registration helpers to the
 * frontend. Custom URL protocols are registered by Wails during packaging.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus returns the current lunacli PATH registration state.
 */
export function GetStatus(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1663595137).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegisterCLIPath adds the lunacli.exe directory to the per-user PATH.
 */
export function RegisterCLIPath(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1398453521).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnregisterCLIPath removes the lunacli registration for the current platform.
 */
export function UnregisterCLIPath(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(4277727328).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PortableSetupStatus.createFrom;
