// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortableSetupService exposes the lunabox:// protocol and lunacli PATH
 * registration helpers to the frontend. It only meaningfully operates on
 * Windows; on other platforms (or in installer builds) the GetStatus call
 * still works and returns a disabled state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus returns the current registration state for the protocol handler
 * and the lunacli PATH entry.
 */
export function GetStatus(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1663595137).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegisterCLIPath adds the lunacli.exe directory to the per-user PATH.
 */
export function RegisterCLIPath(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1398453521).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegisterProtocol writes (or refreshes) the lunabox:// handler so it points
 * at the currently running executable.
 */
export function RegisterProtocol(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(883375188).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnregisterCLIPath removes the lunacli registration for the current platform.
 */
export function UnregisterCLIPath(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(4277727328).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnregisterProtocol removes the lunabox:// handler.
 */
export function UnregisterProtocol(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1163952871).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PortableSetupStatus.createFrom;
