// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "./launcher/models.js";

/**
 * CancelProcessSelection 用户取消了进程选择
 * 关闭等待的 channel 并清理临时会话
 */
export function CancelProcessSelection(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(3398673466, gameID);
}

/**
 * CleanupPendingSessions 清理所有待定的进程选择会话
 * 用于程序关闭时的清理，包括：
 * 1. 关闭所有等待的进程选择 channels
 * 2. 停止所有活跃时间追踪
 * 3. 清理数据库中未完成的会话记录
 */
export function CleanupPendingSessions(): $CancellablePromise<void> {
    return $Call.ByID(2007778259);
}

/**
 * EndCurrentPlaySession manually ends LunaBox tracking for the active game.
 * It does not terminate the external game process; it finalizes the current
 * play session and stops monitoring so later process exit cannot write twice.
 */
export function EndCurrentPlaySession(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(2030850023, gameID);
}

/**
 * HandleProtocolLaunch validates and dispatches a protocol-triggered game launch.
 */
export function HandleProtocolLaunch(req: vo$0.ProtocolLaunchRequest): $CancellablePromise<void> {
    return $Call.ByID(3180632300, req);
}

/**
 * NotifyProcessSelected 用户选择了进程后调用此方法通知后端
 * 这会唤醒等待的 goroutine，并在选择稳定 exe 进程时更新数据库
 */
export function NotifyProcessSelected(gameID: string, processName: string): $CancellablePromise<void> {
    return $Call.ByID(162749196, gameID, processName);
}

/**
 * StartGameWithOptions 使用指定选项启动游戏
 * 供 CLI 调用，支持覆盖 LE 和 Magpie 设置
 */
export function StartGameWithOptions(gameID: string, options: launcher$0.LaunchOptions): $CancellablePromise<boolean> {
    return $Call.ByID(2779033485, gameID, options);
}

/**
 * StartGameWithTracking 启动游戏并自动追踪游玩时长
 * 当游戏进程退出时，自动保存游玩记录到数据库
 */
export function StartGameWithTracking(gameID: string): $CancellablePromise<boolean> {
    return $Call.ByID(59990884, gameID);
}
